### ISSUE TITLE
EADDRINUSE

### ISSUE THREAD

**Issue by Fedomer** [foucdeg/x-plane-map-electron#11]
-not working on MacOS.
-Some javascript error on startup 
`Uncaught Exception:
Error: listen EADDRINUSE :::8080
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at /Users/xxxx/Desktop/X-Plane 11/X-Plane-Map.app/Contents/Resources/app.asar/app/background.js:18824:23
    at MapServer.stopListening (/Users/xxxx/Desktop/X-Plane 11/X-Plane-Map.app/Contents/Resources/app.asar/app/background.js:18836:28)
    at MapServer.listen (/Users/xxxx/Desktop/X-Plane 11/X-Plane-Map.app/Contents/Resources/app.asar/app/background.js:18822:12)
    at App.<anonymous> (/Users/xxxx/Desktop/X-Plane 11/X-Plane-Map.app/Contents/Resources/app.asar/app/background.js:14261:15)
    at emitTwo (events.js:111:20)`

**Comment by foucdeg** [comment]
The error indicates that something else on your computer is listening on port 8080, which is a port we are trying to use.
Do you get to the setup page? If you do, in Advanced Setup, change port 8080 to 8081 or any other between 1024 - 65535. That should make things work.

I need to improve the default behaviour when a default port is unavailable. I guess the app could try a few different ports until it finds one available.

**Comment by foucdeg** [comment]
@Fedomer Version 2.2.0 will prevent users from choosing unavailable ports. Please download it :) Closing this.
